export const chatData = [
    {
        "chatbotid": [
          {
            "id": -1,
            "numChoice": 6,
            "query1": "Apa Kabar",
            "query2": "Self Acceptance",
            "query3": "Body Image",
            "query4": "Tentang Makanan",
            "query5": "Tentang Eating Disorder",
            "query6": "Lihat pilihan lain",
            "refer1": 1,
            "refer2": 2,
            "refer3": 3,
            "refer4": 4,
            "refer5": 5,
            "refer6": 0,
            "text": "Hai Meddy, namaku Melly, apa yang bisa aku bantu hari ini? Meddy bisa mengetikkan pesan-pesan ini supaya aku bisa merespon dengan baik. \n1. Apa Kabar \n2. Self Acceptance \n3. Body Image \n4. Tentang Makanan \n5. Tentang Eating Disorder \n6. Lihat pilihan lain"
          },
          {
            "id": 0,
            "numChoice": 6,
            "query1": "I'm not okay",
            "query2": "Cari tau tentang mealth",
            "query3": "Bagaimana cara aku berkontribusi",
            "query4": "Fun facts",
            "query5": "Mau tau lebih banyak tentang mealth",
            "query6": "Kembali ke Halaman Sebelumnya",
            "refer1": 6,
            "refer2": 7,
            "refer3": 8,
            "refer4": 9,
            "refer5": 10,
            "refer6": -1,
            "text": "Hal-hal lain yang bisa Meddy tanyakan ke Melly \n1. I'm not okay \n2. Cari tau tentang mealth \n3. Bagaimana cara aku berkontribusi \n4. Fun facts \n5. Mau tau lebih banyak tentang mealth \n6. Kembali ke Halaman Sebelumnya"
          },
          {
            "id": 1,
            "numChoice": 2,
            "query1": "Aku lagi bahagia nih",
            "query2": "Aku lagi sedih ni",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 11,
            "refer2": 12,
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Wah, Melly lagi seneng banget nih hari ini! Melly mau tau dong kabar Meddy gimana? \n1. Aku lagi bahagia nih \n2. Aku lagi sedih ni"
          },
          {
            "id": 2,
            "numChoice": 3,
            "query1": "Melly, aku Insecure nih",
            "query2": "Gimana cara untuk mulai menerima diri sendiri",
            "query3": "Gimana ya biar aku ga bandingin diriku sama orang terus",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 13,
            "refer2": 14,
            "refer3": 15,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hi, apa yang ingin Meddy ketahui tentang Self Acceptance nih? \n1. Melly, aku Insecure nih \n2. Gimana cara untuk mulai menerima diri sendiri \n3. Gimana ya biar aku ga bandingin diriku sama orang terus"
          },
          {
            "id": 3,
            "numChoice": 3,
            "query1": "Apa itu body image?",
            "query2": "Apa itu positive body image?",
            "query3": "Bagaimana cara memiliki positive body image?",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 16,
            "refer2": 17,
            "refer3": 18,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hi Meddy! Penting loh untuk tau informasi tentang Body Image untuk lebih mensyukuri diri sendiri! Silahkan ketik dan kirim informasi yang Meddy butuhkan ya \n1. Apa itu body image? \n2. Apa itu positive body image? \n3. Bagaimana cara memiliki positive body image?"
          },
          {
            "id": 4,
            "numChoice": 3,
            "query1": "Pola makan yang sehat",
            "query2": "Rekomendasi Makanan Hari Ini",
            "query3": "Tips Diet",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 19,
            "refer2": 20,
            "refer3": 21,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hi! Meddy ingin tahu apa tentang makanan ni? \n1. Pola makan yang sehat \n2. Rekomendasi Makanan Hari Ini \n3. Tips Diet"
          },
          {
            "id": 5,
            "numChoice": 4,
            "query1": "Apa itu eating disorder",
            "query2": "Apa saja jenis eating disorder",
            "query3": "Kenapa eating disorder bisa terjadi",
            "query4": "Apakah aku punya eating disorder",
            "query5": "",
            "query6": "",
            "refer1": 36,
            "refer2": 37,
            "refer3": 38,
            "refer4": 39,
            "refer5": "",
            "refer6": "",
            "text": "Hi Meddy! Kamu mau nanya apanih ke Melly soal eating disorder? \n1. Apa itu eating disorder \n2. Apa saja jenis eating disorder \n3. Kenapa eating disorder bisa terjadi \n4. Apakah aku punya eating disorder"
          },
          {
            "id": 6,
            "numChoice": 3,
            "query1": "Cerita ke orang lain",
            "query2": "Cerita ke Ahli",
            "query3": "Gabung komunitas",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 22,
            "refer2": 23,
            "refer3": 24,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hi, Melly cukup sedih dengarnya, mungkin Meddy bisa nih coba cara berikut yang dapat membantu Meddy meringankan beberapa masalah Meddy\n1. Cerita ke orang lain \n2. Cerita ke Ahli \n3. Gabung komunitas"
          },
          {
            "id": 7,
            "numChoice": 3,
            "query1": "Mealth itu apa sih",
            "query2": "Event Mealth",
            "query3": "Komunitas Mealth",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 25,
            "refer2": 26,
            "refer3": 27,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hai! Banyak info nih tentang Mealth, Meddy mau tau yang mana?\n1. Mealth itu apa sih \n2. Event Mealth \n3. Komunitas Mealth"
          },
          {
            "id": 8,
            "numChoice": 2,
            "query1": "Bangun lingkungan yang positif",
            "query2": "Aktif terlibat dan sebarkan informasi",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 28,
            "refer2": 29,
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Terimakasih ya, udah mau bantu Melly buat berkontribusi menyelesaikan permasalahan eating disorder ini! Meddy bisa bantu Melly dengan berbagai cara loh, bisa Meddy lihat detailnya di bawah ini\n1. Bangun lingkungan yang positif \n2. Aktif terlibat dan sebarkan informasi"
          },
          {
            "id": 9,
            "numChoice": 3,
            "query1": "Fact A",
            "query2": "Fact B",
            "query3": "Fact C",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 30,
            "refer2": 31,
            "refer3": 32,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Wah, Melly senang karena Meddy rasa ingin tahunya cukup tinggi! Ada beberapa funfact tentang eating disorder nih yang bisa Meddy ketahui!\n1. Fact A \n2. Fact B \n3. Fact C"
          },
          {
            "id": 10,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
<<<<<<< Updated upstream
            "text": "Klik link dibawah ini ya!\n1. Join Community Mealth https://bit.ly/MealthGroupCommunity. \nInstagram Mealth https://www.instagram.com/mealth_id/. \nKonsultasi dengan psikolog ? link ke page consultation"
=======
            "text": "Klik link dibawah ini ya!\\n1. Join Community Mealth https://bit.ly/MealthGroupCommunity. \\n2. Instagram Mealth https://www.instagram.com/mealth_id/. \\n3. Konsultasi dengan psikolog? mealth.netlify.app/Konsultasi"
>>>>>>> Stashed changes
          },
          {
            "id": 11,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Wah, Melly turut senang kalo Meddy lagi bahagia nih! Semoga Meddy kedepannya bisa terus bahagia, selalu bersyukur, dan bisa menjadi diri Meddy yang terbaik setiap harinya!"
          },
          {
            "id": 12,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "It's okay Meddy, wajar banget kok untuk merasakan sedih, just take your time! Kadang rasa sedih juga bisa membuat diri kita belajar sesuatu yang baru. Percaya aja, apa pun yang lagi dilalui, semua pasti ada jalan keluarnya! \n\nJust friendly reminder dari Melly, kalau hidup itu gak akan selalu sempurna. Kadang hidup ga berjalan sesuai dengan rencana kita. Tapi, kita bisa belajar untuk bahagia dengan cara mensyukuri yang ada \n\nDan Melly berharap dan percaya kalau masa-masa berat di hidupmu akan segera berlalu. Meskipun terasa panjang, nikmatin prosesnya, kamu pasti bisa kok. Karena kalau dipikir-pikir, segala sesuatu pasti ada akhirnya! Semangat Meddy, sending virtual hugs!"
          },
          {
            "id": 13,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hi Meddy, untuk merasakan sedih, merasa kurang, tidak bisa melakukan sesuatu dengan benar, itu normal kok. Tapi merasa insecure berkepanjangan ga baik loh karena secara nggak sadar, itu bisa mempengaruhi performa bahkan kesehatan kamu. \n\nTerlebih lagi, kamu ga bisa membandingkan diri kamu sama orang lain, Meddy. Kamu cuma layak membandingkan dengan diri kamu yang sebelumnya. Ingat, kamu berharga! Dan seharusnya kamu bangga sama semua yang pernah kamu lalui dan kamu capai."
          },
          {
            "id": 14,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Self acceptance itu adalah ketika tidak lagi membandingkan diri dengan orang lain. Coba mulai dengan mengenali diri sendiri, kasih waktu untuk diri kamu. Coba berbagai aktivitas, cari tau apa yang kamu suka, apa kelebihan kamu, dan fokuslah sama kelebihan itu. \n\n Tapi menerima diri tidak berhenti sampai situ, tapi berusaha untuk menjadi the best version of you. Self acceptance berarti untuk terus mengembangakan diri menjadi yang lebih baik. Dan tentunya untuk bangga dan mengekspresikan diri kamu!"
          },
          {
            "id": 15,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Kamu harus bisa menerima kekurangan yang kamu punya dan menyadari kelebihan yang kamu miliki. Dengan menerima semua yang kamu miliki, kamu akan sadar bahwa akhirnya setiap orang di dunia ini dilahirkan berbeda Meddy! \n\nBahwa kamu nggak bisa membandingkan dirimu dengan orang lain. Pada akhirnya, kita dilahirkan dengan tujuan yang tentu berbeda di muka bumi ini. Jadi, belajar berdamai, menerima, dan bersyukur sama dirimu sendiri. Cobalah menyadari, akan betapa berharganya dirimu, Meddy!"
          },
          {
            "id": 16,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Body Image atau citra tubuh adalah kombinasi dari pikiran dan perasaan yang dimiliki terhadap tubuh kita. Body image setiap orang itu bisa berbeda baik positif, negatif, maupun kombinasi keduanya. Namun, memang penting dan disarankan untuk bisa memiliki positive body image, Meddy.  \n\nBody image dapat dipengaruhi oleh faktor internal (misalnya kepribadian) dan eksternal (misalnya lingkungan sosial)."
          },
          {
            "id": 17,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Positive body image adalah ketika kamu bisa menerima, mengapresiasi, dan menghormati tubuhmu sendiri. Berbeda dengan Body Satisfaction, ketika kamu tidak sepenuhnya puas terhadap tubuhmu tetapi masih dapat menerimanya. \n\nPositive Body Image berkaitan dengan penerimaan diri, kepercayaan diri, dan memiliki perilaku sehari-hari yang sehat yang ditunjukkan dengan memiliki praktik makan dan olahraga yang sesuai dengan kebutuhan."
          },
          {
            "id": 18,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "1. Fokus pada kualitas, kemampuan, dan talentamu \n2. Hindari negative self-talk. Berikan apresiasi dan hargai dirimu sendiri! \n3. Fokus pada kesehatan bukan pada angka di timbangan. \n4. Unfollow orang-orang yang memicu pikiran negatif terhadap dirimu sendiri."
          },
          {
            "id": 19,
            "numChoice": 3,
            "query1": "Pola makan yang sehat itu gimana",
            "query2": "Mindset pola makan yang benar itu seperti apa?",
            "query3": "Tips pola makan yang sehat",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 33,
            "refer2": 34,
            "refer3": 35,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hi Meddy! Kamu mau tau apa nih soal pola makan?\n 1. Pola makan yang sehat itu gimana?\n 2. Mindset pola makan yang benar itu seperti apa?\n 3. Tips pola makan yang sehat"
          },
          {
            "id": 20,
            "numChoice": 3,
            "query1": "Makan siang",
            "query2": "Snack",
            "query3": "Makan malam",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 40,
            "refer2": 41,
            "refer3": 42,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Hai Meddy, Melly ada beberapa rekomendasi nih untuk kamu, btw kamu mau jenis makanan apa nih?\n 1. Makan siang\n 2. Snack\n 3. Makan malam"
          },
          {
            "id": 21,
            "numChoice": 3,
            "query1": "Mindset diet yang benar",
            "query2": "Energi yang seimbang",
            "query3": "Olahraga",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": 43,
            "refer2": 44,
            "refer3": 45,
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Wah, Melly seneng banget berbagi tips ke Meddy! Apalagi seputar diet.\n 1. Mindset diet yang benar\n 2. Energi yang seimbang\n 3. Olahraga"
          },
          {
            "id": 22,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Menurut riset, cerita orang lain sangat bermanfaat, yaitu dapat memberi rasa tenang, tidak merasa sendirian, mendapatkan support, serta yang terpenting mendapatkan masukan dan solusi dari orang-orang sekitar. Selain itu, bercerita ke orang lain dapat menurunkan risiko stress atau tertekan serta meningkatkan rasa percaya diri dan menghargai diri sendiri."
          },
          {
            "id": 23,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Cerita kepada professional atau ahli dapat menjadi salah satu langkah yang sangat tepat bagi kamu yang merasa tidak nyaman cerita ke orang sekitar atau tidak merasa menemukan solusi setelah bercerita. Professional dapat membantu kamu untuk menemukan akar permasalahan kamu dan memberikan arahan yang tepat untuk kamu untuk menyelesaikan permasalahan ini. Dan ga ada salahnya kok Meddy!"
          },
          {
            "id": 24,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Berada di sebuah komunitas dengan orang-orang yang mengerti situasi kamu bisa jadi salah satu jalan keluarnya. Selain mendapatkan teman cerita baru, dengan komunitas kamu dapat menambah tingkat kepercayaan diri. Dengan komunitas yang suportif, Meddy juga dapat menjadikan tempat ini sebagai zona aman dan nyaman. Nah, kalo Meddy tertarik, Meddy bisa nih join ke komunitas Mealth pada link berikut https://bit.ly/MealthGroupCommunity"
          },
          {
            "id": 25,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Mealth adalah sebuah community based platform yang bertujuan meningkatkan awareness tentang Eating Behavior (Eating Disorder) dan berkontribusi dalam membantu masyarakat Indonesia untuk bisa sehat secara fisik dan mental."
          },
          {
            "id": 26,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Mealth punya beberapa event seru lho yang bisa kamu ikuti! Mulai dari :\n1. Menambah insight dan pengetahuanmu dengan ikut Webinar berisi materi-materi insightful!\n2. Ngobrol dan diskusi santai di Talkshow bersama para ahli di bidangnya!\n3. Curahkan isi hatimu dan masalah yang kamu alami di Mealthouse!\n4. Ikuti Challenge dari Mealth untuk dapatkan hadiah setiap bulannya!"
          },
          {
            "id": 27,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Yuk bergabung bersama komunitas Mealth yang akan menyediakan tempat yang aman, nyaman, dan suportif untuk bercerita dan melalui permasalahan yang kamu alami. Selain itu, kamu juga bisa memperluas koneksi dengan orang-orang yang juga memiliki permasalahan yang sama!"
          },
          {
            "id": 28,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Di dalam komunitas nanti, Meddy dapat berinteraksi, bertukar kabar, menanggapi cerita teman-teman, dan turut serta memberikan support satu sama lain dalam kondisi apapun.\nOiya, perlu diingat untuk tidak memberikan apresiasi kepada anggota Mealth yang mengalami penurunan badan namun dengan pola diet yang tidak baik. Karena di Mealth yang terpenting bukan siapa yang paling cepat dan banyak menaikkan atau menurunkan berat badan. Disini, kita sama-sama membangun mental dan mindset yang baik dalam menerima diri kita agar terhindar dari kebiasaan buruk."
          },
          {
            "id": 29,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Kamu bisa ikut berkontribusi untuk menyelesaikan permasalahan eating disorder dengan membantu menyebarkan informasi lewat sosial mediamu. Agar kedepannya, semakin banyak orang yang tahu dan semakin banyak orang yang tersadarkan tentang isu Eating Disorder!"
          },
          {
            "id": 30,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Tahukah kamu, kalau 75% orang yang menderita eating disorder tidak mencari pertolongan profesional loh Meddy! Padahal masalah ini bukan masalah sederhana dan butuh penanganan segera dari professional."
          },
          {
            "id": 31,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Tahu nggak Meddy, kalau dua pertiga remaja putri dari segala usia tidak puas dengan berat badan mereka, yang menyebabkan mereka rentan memiliki perilaku pengendalian berat yang cenderung berbahaya. Makanya penting loh Meddy untuk memiliki body image yang benar dan untuk bisa menerima diri sendiri."
          },
          {
            "id": 32,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Ternyata kebiasaan makan kamu tuh juga dipengaruhi oleh faktor genetik! Apa aja?\n1. Sistem Metabolisme. Biasanya, Meddy yang makan banyak, tapi tetap kurus, atau makan sedikit jadi mudah naik beratnya, karena sistem metabolisme ini. Meskipun ini genetik, tapi tetep bisa kok diatur dengan olahraga.\n2. Selera Makan. Nah, kalo selera makan ini terjadi karena perbedaan genetik seperti kepadatan papila rasa, sensitivitas reseptor rasa, hingga konstituen air liur."
          },
          {
            "id": 33,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Pola makan sehat itu bukan berarti makan dengan kalori tertentu, tetapi makan dengan bijak. Untuk tidak merasa bersalah ketika makan yang manis, yang berkalori tinggi, karena tubuh kamu sebenarnya butuh itu semua! Tapi harus diingat untuk bisa mengontrol diri ketika makan dan memastikan asupan makanan kamu seimbang. \n\nPola makan yang sehat juga berarti memiliki hubungan yang baik dengan makanan. Tidak merasa bersalah atau takut ketika makan. Karena ingat, pada akhirnya kamu butuh makan, Meddy!"
          },
          {
            "id": 34,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "1. Bisa menikmati makanan dengan porsi yang bijak.\n2. Tidak melabeli satu makanan itu sehat atau tidak sehat karena pada dasarnya semua makanan itu baik asalkan memerhatikan cara pengolahan, waktu makan, dan porsi makan.\n3. Peka sama sinyal yang dikasih tubuh, baik itu kesehatan fisik maupun mental. Kalau dirasa ada yang tidak baik, sekecil apapun, coba evaluasi kebiasaan kamu."
          },
          {
            "id": 35,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Sedikit tips langsung dari ahli gizi, pertama, ketika masak, lebih baik untuk menuangkan bumbu penyedap di akhir. Kedua, makanan lebih baik ketika mendekati rasa dan bentuk aslinya. Sebagai contoh, lebih baik makan buah potong dibanding buah yang dijus. Selain itu, ketika memasak penting untuk mengganti minyak goreng, jangan dipakai berulang kali terus. Terakhir, disarankan untuk makan terakhir kali di 3 jam sebelum tidur. Kalau mau tau lebih banyak, cek Instagram @mealth_id yah!"
          },
          {
            "id": 36,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Eating Disorder adalah serangkaian kondisi psikologis yang menyebabkan berkembangnya kebiasaan makan yang tidak sehat. Biasanya diawali dengan terobsesi pada makanan, berat badan, atau bentuk tubuh. Hal ini dapat berdampak negatif bagi kesehatan fisik dan mental seseorang. Perlu diingat bahwa eating disorder bukan hal yang sederhana, harus di diagnosis dan diberi penanganan yang tepat oleh ahlinya! \n\nBerdasarkan data di tahun 2019, ada sekitar 400.000 orang Indonesia yang mengalami eating disorder. Sayangnya, masih banyak masyarakat Indonesia yang masih menganggap hal ini tabu, bahkan banyak yang tidak tau tentang isu ini. Padahal bisa jadi ada orang-orang di sekitarmu yang juga mengalami eating disorder. Yuk sama-sama tingkatkan kesadaran dan bantu mereka yang sedang mengalami eating disorder dengan Mealth."
          },
          {
            "id": 37,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Eating Disorder tuh ada banyak jenisnya loh, Meddy!  Mulai dari bulimia nervosa (makan dalam jumlah banyak lalu dimuntahkan dengan sengaja) , anorexia nervosa (penurunan berat badan secara ekstrim yang diikuti rasa takut untuk makan), binge eating disorder (makan dalam jumlah besar secara berulang), PICA (kebiasaan mengonsumsi benda bukan makanan), rumination (memuntahkan makanan lalu dimakan kembali, lalu memuntahkan dan memakannya kembali), dan masih banyak lagi. \n\nPerlu diingat yah Meddy bahwa kamu tidak bisa mendiagnosis diri kamu sendiri. Harus ahli yang bisa mendiagnosis apakah kamu memiliki eating disorder atau tidak karena eating disorder adalah keadaan yang kompleks.  Jangan sampai kamu self-diagnose karena tidak baik buat diri kamu sendiri, Meddy! Dan ga ada salahnya kok mencari bantuan langsung kepada mereka yang benar-benar mengerti, seperti psikolog, psikiater, ahli gizi, ataupun dokter."
          },
          {
            "id": 38,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Eating disorder bisa terjadi karena adanya rasa kurang percaya diri dan persepsi yang buruk dalam memandang diri sendiri. Ditambah dengan persepsi untuk harus berpenampilan sesuai dengan standar kecantikan. Padahal, kecantikan orang itu ga ada standarnya! Sayangnya, hal ini dapat menyebabkan perasaan takut ketika berat badan naik hingga ketika makan. Bisa juga disebabkan dengan hilangnya kontrol ketika makan."
          },
          {
            "id": 39,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Ingat yah Meddy jangan pernah mendiagnosis dirimu sendiri! Tetapi tidak salah untuk cek apakah kamu memiliki kecenderungan atau tidak agar dapat cepat mendapatkan bantuan. Buat Meddy yang penasaran, bisa klik di link berikut https://bit.ly/EatingDisorderTest . Harus diingat kalau hanya ahli yang dapat mendiagnosis kamu, jadi lebih baik langsung pastikan kepada mereka yah."
          },
          {
            "id": 40,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Gado-gado\nBagi Meddy yang mau makan siang yang ringan dan sehat, gado-gado adalah jawabannya. Paduan kentang dengan beragam sayuran segar dan bumbu kacang sangat cocok untuk di siang hari.\n\nAglio Olio\nUntuk Meddy yang mau masak anti ribet, aglio olio dapat menjadi jawabannya. Khasnya rasa bawang ditambah dengan irisan daging asap, cocok di makan di siang hari.\n\nNasi Padang\nNasi padang dengan porsinya yang besar dan bumbunya yang khas, dapat menjadi pilihan ketika Meddy butuh makan berat di siang hari."
          },
          {
            "id": 41,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Spring Roll Vietnam\nNah, Meddy juga bisa cobain nih fresh spring roll, perpaduan sayuran segar, udang, dan bihun, dibalut dengan rice wrapper ditambah dengan saus kacang yang lezat, fix Meddy pasti suka banget.\n\nSalad Buah\nSalad Buah adalah makanan yang sehat dan segar. Selain itu, salad buah memiliki banyak vitamin. Maka dari itu, makanan ini sangat cocok untukmu.\n\nOat Snack\nUntuk Meddy yang mau snack rendah kalori, bisa cobain Oat Snack nih. Selain itu, Oat Snack dapat memberikan rasa kenyang untuk Meddy."
          },
          {
            "id": 42,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Sirloin Steak\nBagi Meddy pecinta daging sapi, sirloin steak dapat menjadi salah satu menu makan malam yang tepat. Selain itu, Meddy dapat menambahkan sayuran buncis atau olahan kentang sebagai karbohidrat.\n\nSate\nSate merupakan salah satu opsi terbaik untuk makan malam nih. Meddy bisa pilih jenis sate dan jenis bumbunya sesuai dengan preferensi Meddy!\n\nTom Yam\nTom Yam cocok banget nih bagi Meddy yang suka makanan-makanan khas Thailand. Rasanya yang sedikit asam ditambah dengan sayuran dan beberapa jenis olahan laut pas banget untuk nemenin makan malam Meddy!"
          },
          {
            "id": 43,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Dalam diet, kita harus memiliki mindset yang tepat. Hal yang pertama adalah untuk memiliki mindset diet untuk tujuan kesehatan bukan hanya untuk sembarang mengurangi timbangan berat badan. Health is not a look! Dan ingat ya Meddy, badan kurus itu bukan berarti sehat loh.\n\nDimulai dengan menghindari pola diet yang ekstrim apalagi sampai membahayakan kesehatan tubuh. Misalnya, pake obat diet karena hasilnya hanya bersifat sementara. Kalau mau hasil yang lebih stabil bagaimana? Cari pola diet yang benar dan yang dapat kamu jalani dengan konsisten. Gaperlu yang ekstrim, yang penting kamu nyaman menjalaninya dan tentunya sudah terbukti sehat dan mana. Setelah kamu mencapai target, tetap konsisten dengan menerapkan lifestyle yang baru supaya diet kamu bukan diet yo-yo alias akan balik lagi ke semula."
          },
          {
            "id": 44,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Saat Meddy ingin menaikkan berat badan, Meddy perlu dalam kondisi kalori surplus. Dimana kalori masuk lebih banyak daripada kalori yang keluar. Begitu juga sebaliknya, saat Meddy ingin menurunkan berat badan. Tapi, Meddy perlu tahu batas minimal kalori masuk berapa dengan kalkulator TDEE https://tdeecalculator.net/ . Tapi ingat jangan sampai berlebihan yah, Meddy! Jangan lupa untuk be mindful!\n\nEits! Tapi Meddy gaboleh semata-mata hanya melihat kalori nya saja ya! Meddy juga perlu memperhatikan dari sisi macronutrients nya juga seperti:\nAsupan protein untuk menjaga nilai massa otot\nAsupan lemak sehat untuk menyimpan energi dalam tubuh\nAsupan karbohidrat juga sebagai sumber energi tubuh dalam berkegiatan\n\nKalau masih bingung, jangan takut untuk langsung konsultasi dengan ahlinya! Biar memastikan mana yang baik dan benar."
          },
          {
            "id": 45,
            "numChoice": 0,
            "query1": "",
            "query2": "",
            "query3": "",
            "query4": "",
            "query5": "",
            "query6": "",
            "refer1": "",
            "refer2": "",
            "refer3": "",
            "refer4": "",
            "refer5": "",
            "refer6": "",
            "text": "Selain mengatur pola makan, Meddy juga harus mengatur gaya hidup dengan olahraga yang lebih sering. Baiknya, olahraga sebanyak 150 menit/minggu atau sekitar 30 menit /hari dalam 5 hari seminggu.\nNamun, jika Meddy merasa itu terlalu berat, boleh kok mulai dengan durasi yang lebih singkat dan perlahan-lahan ditingkatkan. Intinya, harus konsisten!"
          }
        ]
      }
]